name: FASurvival
version: '1.0-SNAPSHOT'
main: fr.kenda.fasurvie.FASurvival
api-version: '1.16'
load: POSTWORLD
authors: [ Kenda ]
commands:
  FAsurvival:
    aliases:
      - fas
      - FAsurvie
      - FA
  FAManual:
    aliases:
      - aide
      - manual
      - manuel